version: '3'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_portfolio
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
